project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - "Chapter Landing Pages/*.qmd"
    - "Chapter Slides/*.qmd"
  resources:
    - data/
    - images/
    - apps/
    - R/
    - .nojekyll

website:
  title: "ANOVA"
  site-url: "https://nishanmudalige.github.io/UQ_Teaching_Demo"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Chapter Landing Pages/anova-landing.qmd
        text: Chapter page
      - href: Chapter Slides/anova-chapter.qmd
        text: Slides
      - href: data/incubation_data.csv
        text: Data

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    code-fold: true
    format-links: false
    include-in-header: mobile-zoom.html
